### ISSUE TITLE
Pilot for image data

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#1087]
### Description

As a user, I want to be able to access image data for the models where available

Pilot dataset:  JAX images

Documentation: 
- [Submission process](https://docs.google.com/document/d/1Od6AWMQs803yeHyHFXWWSOYMG_KjLXv37m3WZ0Zmkuc/edit)

### Acceptance criteria

- [x] pilot submission of image dataset to BIA 
- [x] link to the pilot dataset from CancerModels.Org
- [x] SOP for image data submissions for CancerMOdels.Org providers
