### ISSUE TITLE
Pilot cBioPortal instance in CancerModels.org

### ISSUE THREAD

**Issue by Mandloi2309** [PDXFinder/pdxfinder#1109]
### Description

As a Bioinformatician, I want to have a local version cBioPortal to be able to provide users with tools for data analysis and to add value to the resource.

REPO https://gitlab.ebi.ac.uk/mouse-informatics/pdcm-cbioportal
### Acceptance criteria

- [x] Setup cbioportal instance locally
- [x] Generate metadata and data files for study
- [x] Molecular data transformation
- [x] Deploy to K8
- [x] Test deployment
- [x] Request mappings from web-prod for making it user facing
