### ISSUE TITLE
Data assessment and quality

### ISSUE THREAD

**Issue by Mandloi2309** [PDXFinder/pdxfinder#1128]
### Description

As a bioinformatician, I want to make an assessment of different data available for current providers to improve the data quality and resource value.

### Acceptance criteria

- [x] Data assessment
- [ ] Fetching of (meta) data 
- [ ] New data types acquired
- [ ] Data model changes
- [ ] Documentation

**Comment by Mandloi2309** [comment]
Data assessment: https://docs.google.com/spreadsheets/d/1RraJDido9PFtEFKkQSAYASQwDN8FOTWmGM2aZYawxe8/edit#gid=0
