### ISSUE TITLE
Extend validator for metadata template

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#389]
### Description

As a developer, I want to have an automatic validator for metadata template independent of data loading

Previous planned implementation for the validator (Ross stuff): https://www.ebi.ac.uk/seqdb/confluence/display/MouseInformatics/Data+Validation

Previously recorded ideas for the validation service (Alex stuff) : https://docs.google.com/document/d/1J1eLDvqQkdsXN_aUadYta07jEpHHtVZO_g3qHtUOjE8/edit#heading=h.m8o790lq2135

Epic Episode 1: The Spreadsheet Menace
- [x] Ticket for validation documentation completion #396
- [x] Ticket for testing #397 (closed)
- [x] Ticket for adding/checking software features for basic rules #395 (closed)

- [x] Finnish value restrictions #441
- [x] Clean logs #442

Epic Episode 2: Attack of the Architecture
- [x] Remove validator from Index #578
- [x] containerize Validator and write API
- [x] set up on Kubes
- [x] Ticket to discuss validator architecture #398

Epic Episode 3: Revenge of the Code Base
- [x] Complete Star Wars trilogy puns

**Comment by zperova** [comment]
@zperova make a doc with metadata context validation rules

**Comment by Afollet** [comment]
@zperova tickets written.

**Comment by zperova** [comment]
👍 for puns
